version: '3'

services:
  dev:
    build:
      dockerfile: dockerfile.dev
    volumes:
      - .:/code
    ports:
      - 8001:8001
      - 8080:8080
    stdin_open: true # docker run -i
    tty: true        # docker run -t