version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    volumes:
      - .:/code
    ports:
      - 8001:8001
    command: python manage.py runserver 0.0.0.0:8001
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    volumes:
      - .:/code
    ports:
      - 8080:8080
    command: npm run serve
    depends_on:
      - backend
